language: java
sudo: required
dist: trusty
group: edge
before_install:
  - if [[ ${TRAVIS_JDK_VERSION} == "openjdk9" ]]; then jdk_switcher use openjdk9; fi
  - if [[ ${TRAVIS_JDK_VERSION} == "oraclejdk9" ]]; then jdk_switcher use openjdk9; fi
  - gradle -version
jdk:
  - oraclejdk8
  - oraclejdk9
matrix:
  allow_failures:
    - jdk: oraclejdk9

after_success:
  - ./gradlew jacocoTestReport coveralls
