language: java
sudo: required
dist: trusty
group: edge
before_install:
  - echo $TRAVIS_JDK_VERSION
  - echo $JAVA_HOME
  - gradle -version
jdk:
  - oraclejdk8
  - oraclejdk9
matrix:
  allow_failures:
    - jdk: oraclejdk9

after_success:
  - ./gradlew jacocoTestReport coveralls
