language: java
sudo: required
dist: trusty
group: edge
branches:
  except:
    - jdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk:
  - oraclejdk8
  - oraclejdk9

after_success:
  - ./gradlew jacocoTestReport coveralls
