version: '{build}'
skip_tags: true

build_script:
    - gradlew.bat assemble

branches:
  only:
    - master

test_script:
    - gradlew.bat check

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
    fast_finish: true
